version: '3.8'

services:
  backend:
    build:
      context: ./DevPlatform.Server
      dockerfile: DockerFile
    ports:
      - "8080:5057"
      - "8443:7228"
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/certs/DevPlatform.Server.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /app/certs/DevPlatform.Server.key
      ASPNETCORE_URLS: "https://localhost:7228;http://localhost:5057"
    networks:
      - devplatform

  frontend:
    build:
      context: ./devplatform.client
      dockerfile: DockerFile
    ports:
      - "3080:3000"
      - "3443:58604"
    environment:
      NODE_EXTRA_CA_CERTS: /app/certs/DevPlatform.Server.pem
      HTTPS: "true"
      SSL_CRT_FILE: /app/certs/devplatform.client.pem
      SSL_KEY_FILE: /app/certs/devplatform.client.key
    networks:
      - devplatform

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - devplatform
  
networks:
  devplatform:
    driver: bridge