version: '3.8'

services:
  backend:
    build:
      context: ./DevPlatform.Server
      dockerfile: DockerFile
    ports:
      - "5057:8080"
      - "7228:8081"
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/DevPlatform.Server.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/DevPlatform.Server.key
      ASPNETCORE_URLS: "https://+:8080;http://+:8081"

  frontend:
    build:
      context: ./devplatform.client
      dockerfile: DockerFile
    ports:
      - "3000:80"
      - "58604:443"
    environment:
      NODE_EXTRA_CA_CERTS: /https/DevPlatform.Server.pem
      HTTPS: "true"
      SSL_CRT_FILE: /https/devplatform.client.pem
      SSL_KEY_FILE: /https/devplatform.client.key
