# Используем базовый образ для Node.js
FROM node:20 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package.json package-lock.json ./
RUN npm install

# Копируем остальные файлы и собираем приложение
COPY . .
RUN npm run build
COPY certs /app/certs
# Используем базовый образ для Nginx
#FROM nginx:alpine
#COPY --from=build /app/dist /usr/share/nginx/html

# Копируем конфигурационный файл Nginx
# COPY nginx.conf /etc/nginx/nginx.conf

# Копируем сертификаты
#COPY certs/devplatform.client.pem /etc/nginx/certs/devplatform.client.pem
#COPY certs/devplatform.client.key /etc/nginx/certs/devplatform.client.key
#COPY certs/DevPlatform.Server.key /etc/nginx/certs/DevPlatform.Server.key

# Открываем порт 80
#EXPOSE 80 443

CMD ["npm", "run", "dev", "--", "--host"]

